### ISSUE TITLE
driver cannot be downloaded

### ISSUE THREAD

**Issue by curelesss** [VelsDie/Windows-7-for-Thinkpad-T480-or-any-new-hardware#1]
thanks for providing this repo of Windows 7 drivers for T480. 

For those T480 users who have particular use cases requiring Windows 7 OS, providing tested drivers certainly helps a lot.

however, the torrent method is not working for me, it will be really helpful to upload drivers to google drive, like the OS iso image.

**Comment by VelsDie** [comment]
hey, i am so sorry for not providing a Gdrive link for the drivers in the first place, now you can download the drivers from Gdrive from <a href="https://drive.google.com/file/d/1ITZLzIEb4GfyjshSJrZouPwN1DO5vW8m/view?usp=drive_link">here</a> , goodluck! if you get any other problems/issues, you can contact me again, i would be really happy to help!

**Comment by curelesss** [comment]
thanks
